version: '3.5'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DEFAULT_HOST=$DEFAULT_HOST
      - HTTP_PORT=$NGINX_HTTP_PORT
      - HTTPS_PORT=$NGINX_HTTPS_PORT
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/htpasswd:/etc/nginx/htpasswd
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d:ro
      - $DOCKER_SOCK_PATH:/tmp/docker.sock:ro
    ports:
      - $NGINX_HTTP_PORT:$NGINX_HTTP_PORT
      - $NGINX_HTTPS_PORT:$NGINX_HTTPS_PORT
    networks:
      - nginx
    restart: unless-stopped
  acme:
    image: adferrand/dnsrobocert:latest
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./data/acme/config.yml:/etc/dnsrobocert/config.yml
      - ./data/acme/create_nginx_certs.sh:/usr/local/bin/create-nginx-certs
      - ./data/acme/letsencrypt:/etc/letsencrypt
      - ./data/certs:/etc/nginx/certs
    networks:
      - nginx
    restart: unless-stopped
  whoami:
    image: jwilder/whoami
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - VIRTUAL_HOST=$WHOAMI_HOST
      - VIRTUAL_PORT=8000
    expose: [ 8000 ]
    networks:
      - nginx
    restart: unless-stopped
networks:
  nginx:
    name: nginx
    external: true
