version: '3.6'
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=8080
    volumes:
      - ./data/config:/config
    ports:
      - 6881:6881
      - 6881:6881/udp
    networks:
      - default
    restart: unless-stopped
networks:
  default:
