version: '3.6'
services:
  db:
    image: postgres:13
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  app:
    image: joplin/server:latest
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - APP_PORT=22300
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db
    depends_on: [ "db" ]
    expose: [ 22300 ]
    networks:
      - default
    restart: unless-stopped
networks:
  default:
