version: '3.6'
services:
  api:
    environment:
      - VIRTUAL_HOST=$TG_API_HOST
      - VIRTUAL_PORT=8081
    networks:
      - nginx
  stat:
    image: marcnuri/port-forward
    environment:
      - VIRTUAL_HOST=$TG_STAT_HOST
      - VIRTUAL_PORT=80
      - REMOTE_HOST=api
      - REMOTE_PORT=8082
      - LOCAL_PORT=80
    depends_on: [ api ]
    networks: [ default, nginx ]
  static:
    environment:
      - VIRTUAL_HOST=$TG_STATIC_HOST
      - VIRTUAL_PORT=80
    networks:
      - nginx
networks:
  nginx:
    name: nginx
    external: true
