version: '3.6'
services:
  keeweb:
    image: antelle/keeweb
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - KEEWEB_CONFIG_URL=configs/default.json
    volumes:
      - ./data/configs:/keeweb/configs
      - ./data/certs:/etc/nginx/external
    networks:
      - default
    restart: unless-stopped
networks:
  default:
