version: '3.6'
services:
  backend:
    image: adolfintel/speedtest
    container_name: speedtest_back
    profiles: [ "back" ]
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MODE=backend
      - IPINFO_APIKEY=$IPINFO_APIKEY
    networks:
      - default
    restart: unless-stopped
  frontend:
    image: adolfintel/speedtest
    container_name: speedtest_front
    profiles: [ "front" ]
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MODE=frontend
      - TELEMETRY=true
      - PASSWORD=$TELEMETRY_PASSWORD
      - EMAIL=$EMAIL
      - DB_TYPE=postgres
      - DB_HOSTNAME=db
      - DB_USERNAME=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DATABASE
    depends_on: [ "db" ]
    volumes:
      - ./data/servers.json:/servers.json
    networks:
      - default
    restart: unless-stopped
  db:
    image: postgres:13
    container_name: speedtest_db
    profiles: [ "front" ]
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
networks:
  default:
