version: '3.6'
services:
  nginx:
    image: nginx
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - NGINX_PORT=$NGINX_HTTP_PORT
    volumes:
#      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/templates:/etc/nginx/templates
    restart: unless-stopped
