version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    environment:
      - LC_ALL=$LC_ALL
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVER_NAME=$SERVER_NAME
      - WORLD_NAME=$WORLD_NAME
      - SERVER_PASS=$SERVER_PASS
      - SERVER_PUBLIC=$SERVER_PUBLIC
      - VALHEIM_PLUS=$VALHEIM_PLUS
      - BEPINEX=$BEPINEX
    volumes: 
      - ./data/config:/config
      - ./data/data:/opt/valheim
      - ./data/vhp:/config/valheimplus
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    restart: unless-stopped
    stop_grace_period: 2m
