services:
  es01:
    image: elasticsearch:$VERSION
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=$ELASTIC_ES_JAVA_OPTS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01/data:/usr/share/elasticsearch/data
      - ./data/es01/plugins:/usr/share/elasticsearch/plugins
    expose: [ 9200 ]
    networks: [ default ]
  kib01:
    image: kibana:$VERSION
    environment:
      server.host: "0.0.0.0"
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
    expose: [ 5601 ]
    networks: [ default ]
networks:
  default:
